#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 30 13:17:40 2020

@author: Kieran
"""

def read_file(filename):
    
    import pandas as pd
    
    stretch_imu = pd.read_csv(filename+'/imu/Trial4.csv', header=None)
    emg = pd.read_csv(filename+'/emg/Trial4_emg.csv', header=None)
    amplitude = pd.read_csv(filename+'/Trajectory.csv', header=None)


    amplitude2 = amplitude[amplitude.iloc[:,1] != 0]
    amplitudes = []
    amplitudes.append(amplitude2.iloc[0,1])

    for i in range(len(amplitude2)-1):
        if (amplitude2.iloc[i,1] != amplitude2.iloc[i+1,1]):
            amplitudes.append(amplitude2.iloc[i+1,1])
    
    emg = emg.T

    emg.columns = ['Time','Biceps','Triceps','Deltoid','Pecs']

    stretch_imu = stretch_imu.T

    stretch_imu.columns = ['time','imu','stretch']
    
    return stretch_imu, emg